### ISSUE TITLE
Can i add Line background color ?

### ISSUE THREAD

**Issue by bombkiml** [AndreSouzaAbreu/vue-data-table#75]
Hi, @AndreSouzaAbreu  
How add background-color with some `<tr>` tag ?

something like this.

![image](https://user-images.githubusercontent.com/34172506/208344497-06787cb5-98a6-4a85-bc16-bb2f951c9f55.png)

**Comment by AndreSouzaAbreu** [comment]
Hello!

Well, you can use CSS right? To set a different background on the third row, you could use something like:

```css
table tbody tr:nth-child(3) {
  background-color: 'pink'
}
```

or may be you want diffent background colors for odd and even:

```css
table tbody tr:nth-child(odd) {
  background-color: 'pink'
}

table tbody tr:nth-child(even) {
  background-color: 'blue'
}
```

If you want to put background on the row clicked by the user, you could use `:focus` or `:active` or `:hover`.

More complex logic can be done via JS, by finding the target table row and injecting CSS into it via JS.
